# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT church_restfull.wsgi

beta_settings:
    cloud_sql_instances: church-restfull-psql-db

runtime_config:
  python_version: 3
# [END runtime]
