# Generated by Django 2.0.5 on 2018-06-01 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180601_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
