# Generated by Django 2.0.5 on 2018-05-10 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180510_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Teacher'),
        ),
    ]
